export * from "./generated/api";
// Explicit type re-exports (excluding BrowseStoreProductsParams, which
// collides with the generated zod const of the same name in ./generated/api).
export type {
  AuthResponse,
  DashboardStats,
  DiscountCode,
  DiscountCodeValidationResult,
  DiscountInput,
  DiscountValidation,
  DiscountValidationResult,
  ErrorResponse,
  HealthStatus,
  ListOrdersParams,
  ListProductsParams,
  Merchant,
  MerchantLogin,
  MerchantRegister,
  MerchantUpdate,
  Order,
  OrderConfirmation,
  OrderDetail,
  OrderInput,
  OrderItem,
  OrderItemInput,
  OrderListResponse,
  OrderStatusUpdate,
  Product,
  ProductInput,
  ProductUpdate,
  ProductVariant,
  ProductVariantInput,
  StatusCount,
  StorePublic,
  TopProduct,
} from "./generated/types";

// Additional generated types not listed above, re-exported explicitly to avoid
// colliding with the generated zod consts of the same names in ./generated/api.
export type {
  ProductCreateBody,
  ProductUpdateBody,
  PushSubscriptionInput,
  PushSubscriptionInputKeys,
  VapidPublicKey,
} from "./generated/types";

// Review types (generated by orval; the zod consts of the same names live in
// ./generated/api, so these must be re-exported explicitly too).
export type {
  DashboardReview,
  DashboardReviewsResponse,
  ListReviewsParams,
  ProductReviewInput,
  ProductReviewsResponse,
  Review,
  ReviewDecision,
} from "./generated/types";

// Stock-notification types: same story as above — the zod consts for these
// names live in ./generated/api, so re-export explicitly to avoid collisions.
export type {
  ListStockNotificationsParams,
  StockNotification,
  StockNotificationCreate,
  StockNotificationItem,
  StockNotificationListResponse,
  StockNotificationUpdate,
} from "./generated/types";

// Gift-bundle types: the zod consts for these names live in ./generated/api,
// so re-export explicitly to avoid collisions.
export type {
  Bundle,
  BundleImageResponse,
  BundleInput,
  BundleItem,
  BundleItemInput,
  BundleListResponse,
  UploadBundleImageBody,
} from "./generated/types";

// Store-order tracking types: the zod consts for GetStoreOrderParams and
// GetStoreOrderQueryParams live in ./generated/api, so only TrackOrderResponse
// (which has no matching zod const) is re-exported explicitly.
export type { TrackOrderResponse } from "./generated/types";
